library(reshape2)
library(Rcpp)
setwd(dir="C:/Users/Administrator/Desktop/datasciencecoursera/UCI HAR Dataset")
activityLabels <- read.table("activity_labels.txt")
activityLabels[,2] <- as.character(activityLabels[,2])
features <- read.table("features.txt")
features[,2] <- as.character(features[,2])
featuresdata <- grep(".*mean.*|.*std.*", features[,2])
featuresdata.names <- features[featuresdata,2]
featuresdata.names = gsub('-mean', 'Mean', featuresdata.names)
featuresdata.names = gsub('-std', 'Std', featuresdata.names)
featuresdata.names <- gsub('[-()]', '', featuresdata.names)
train <- read.table("train/X_train.txt")[featuresdata]
trainActivities <- read.table("train/Y_train.txt")
trainSubjects <- read.table("train/subject_train.txt")
train <- cbind(trainSubjects, trainActivities, train)
test <- read.table("test/X_test.txt")[featuresdata]
testActivities <- read.table("test/Y_test.txt")
testSubjects <- read.table("test/subject_test.txt")
test <- cbind(testSubjects, testActivities, test)
allData <- rbind(train, test)
colnames(allData) <- c("subject", "activity", featuresdata.names)
allData$activity <- factor(allData$activity, levels = activityLabels[,1], labels = activityLabels[,2])
allData$subject <- as.factor(allData$subject)
allData.melted <- melt(allData, id = c("subject", "activity"))
allData.mean <- dcast(allData.melted, subject + activity ~ variable, mean)
